name: Code Quality

on:
  pull_request:
    branches: [ mainline, release, feature_assets_cli, 'patch_*' , "feature_*"]
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
      tag:
        required: false
        type: string
      use-cache:
        required: false
        type: boolean
        default: true

jobs:
  Test:
    name: Python
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    # TODO: revert to aws-deadline/.github/.github/workflows/reusable_python_build.yml@mainline
    uses: crowecawcaw/deadline-cloud.github/.github/workflows/reusable_python_build.yml@ci/add-build-caches
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      ref: ${{inputs.tag}}
      use-cache: ${{ inputs.use-cache == '' && true || inputs.use-cache }}

  TestPy38:
    name: Python
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8']
    uses: ./.github/workflows/reusable_python_build_coverage_override.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      ref: ${{inputs.tag}}
      # The incremental output download and mcp feature doesn't run on Python 3.8, so test coverage is lower
      cov-fail-under: "74"
      use-cache: ${{ inputs.use-cache == '' && true || inputs.use-cache }}

  Attributions:
    name: Attributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{inputs.tag}}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: pip
      - run: pip install hatch
      - run: hatch run attributions:check
